name 'development-cookbook'
maintainer 'Jason V. Orona'
maintainer_email 'jasonoron@gmail.com'
license 'all_rights'
description 'Installs/Configures development-cookbook'
long_description 'Installs/Configures development-cookbook'
version '0.1.0'

depends 'yum'
depends 'yumgroup'
depends 'build-essential'
depends 'virtualbox-guest-additions'
depends 'java'
depends 'git'
depends 'idea'
depends 'yum-mysql-community', '~> 0.1.21'
